version: '3.8'
services:
  webserver:
    build: ./docker/php-81-apache-xdebug-31
    ports:
      - "6080:80"
    volumes:
      - ./shop_php:/var/www/html
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop_pass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - .:/var/lib/postgresql/data
    ports:
        - "5432:5432"