version: '3.8'
services:
  webserver:
    build: ./docker/php-81-apache-xdebug-31
    ports:
      - "6080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_USER: user_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33306:3306"
    volumes:
      - ./data:/var/lib/mysql
